DROP TABLE LIBRARY;
DROP TABLE STUDENT;
CREATE TABLE
STUDENT(
sID INT NOT NULL PRIMARY KEY,
fNAME VARCHAR(10),
lNAME VARCHAR(10),
[Age(Atleast 18)] INT NOT NULL CHECK([Age(Atleast 18)] >=18),
Laptop_Owned VARCHAR(3) NOT NULL CHECK(Laptop_Owned = 'YES' OR Laptop_Owned = 'NO'),
Laptop_MAC_id VARCHAR(17) UNIQUE
);
INSERT STUDENT
(SID, [Age(Atleast 18)], Laptop_Owned, Laptop_MAC_id)
VALUES
(1, 18, 'YES', '31-E6-49-8D-71-DD'),
(2, 19, 'YES', 'B3-E1-C4-9F-DE-26'),
(3, 18, 'NO', NULL);
SELECT * FROM STUDENT;

CREATE TABLE
LIBRARY(
BOOK_id INT NOT NULL UNIQUE,
BOOK_TITLE VARCHAR(15) NOT NULL,
[ISSUED_BY_(SID)] INT FOREIGN KEY REFERENCES STUDENT(sID),
crrStat VARCHAR(6) DEFAULT 'ISSUED'
);
INSERT LIBRARY
(BOOK_id, BOOK_TITLE, [ISSUED_BY_(SID)])
VALUES
(1028, 'DBMS', 1),
(1029, 'COA', 2),
(1030, 'OOP', 1),
(1031, 'AM4', 3),
(1032, 'TOC', 2);
CREATE INDEX indexBook_Title
ON LIBRARY (BOOK_TITLE); 
SELECT * FROM LIBRARY;